services:
  - type: web
    name: tree-view-component
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /assets/*.js
        name: Content-Type
        value: text/javascript
      - path: /assets/*.mjs
        name: Content-Type
        value: text/javascript
      - path: /*.js
        name: Content-Type
        value: text/javascript
      - path: /*.mjs
        name: Content-Type
        value: text/javascript
    routes:
      - type: rewrite
        source: /*
        destination: /index.html